name: Ruby Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: [2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 3.0, 3.1, 3.2, 3.3, 3.4]
        exclude:
          # CRuby < 2.6 does not support macos-arm64.
          - { os: macos-latest, ruby: '2.1' }
          - { os: macos-latest, ruby: '2.2' }
          - { os: macos-latest, ruby: '2.3' }
          - { os: macos-latest, ruby: '2.4' }
          - { os: macos-latest, ruby: '2.5' }

    steps:
      - name: Checkout repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@ab177d40ee5483edb974554986f56b33477e21d0 # v1.265.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install --with development

      - name: Run tests
        run: bundle exec rake spec
